add docs
btccom/BTCPoolAPIDocs pull request #1
Opened 2017-02-13 13:53 UTC by PeiyuYang

2017-02-13 15:36 UTC, zzmmzz777 requested changes

2017-02-13 15:36 UTC, ekousp commented on zh-cn.md
> +# BTC.COM 矿池API文档
BTC.COM => BTC.com

2017-02-13 15:36 UTC, ekousp commented on zh-cn.md
> +您的应用可以使用 BTC.COM 提供的矿池API， 实时获取 BTC.COM Pool的运行状态以及用户的帐号详情。
...使用 BTC 矿池提供的 API，实时获取矿池运行状态及用户帐号信息。

2017-02-13 15:36 UTC, ekousp commented on zh-cn.md
> +本API由Domain,Version和Path构成。
修改为：
--

API 调用路径如下：

```
https://${Endpint}/${Version}/${Path}
```

其中：

* Endpoint
  * 中国：`cn-pool.api.btc.com/public`
  * 美国：`us-pool.api.btc.com/public`
* Version: `v1`
* Path: 具体的 API 路径，参见下文定义

2017-02-13 15:36 UTC, ekousp commented on zh-cn.md
> +* 调用用户相关接口时需要提供 AccessKey 和 puid 等相关参数鉴权, AccessKey是身份凭据之一, 请用户保管好自己的AccessKey。
另起二级标题介绍，名称为**鉴权**。
写清楚用户需要在 querystring 中带上，字段为`access_key`。

2017-02-13 15:36 UTC, ekousp commented on zh-cn.md
> +    * AccessKey 和 puid 可以到 pool.btc.com 登录账户，在子账户管理页获取
什么是 puid？解释下。

2017-02-13 15:36 UTC, ekousp commented on zh-cn.md
> +```
标明代码片段类型为 json

2017-02-13 15:36 UTC, ekousp commented on zh-cn.md
> +`GET https://cn-pool.api.btc.com/v1/realtime/hashrate`
换行

2017-02-14 07:43 UTC, zzmmzz777 requested changes

2017-02-14 07:43 UTC, ekousp commented on zh-cn.md
> +## API 调用路径如下：
标题与句子分不清

2017-02-14 07:43 UTC, ekousp commented on zh-cn.md
> +AccessKey是身份凭据之一, 请用户保管好自己的AccessKey。
补充说明 AccessKey 与用户一一对应，而 puid 与子账户对应。

2017-02-14 07:43 UTC, ekousp commented on zh-cn.md
> +AccessKey是身份凭据之一, 请用户保管好自己的AccessKey。
这里缩进不正确。

2017-02-14 07:43 UTC, ekousp commented on zh-cn.md
>  * 所有的响应类型均为`application/json`，如下：
普通句子就可以了，没必要列表。

2017-02-14 08:43 UTC, zzmmzz777 requested changes

2017-02-14 08:43 UTC, ekousp commented on zh-cn.md
> +    * AccessKey与用户一一对应是身份凭据之一, 请用户保管好自己的AccessKey。
AccessKey 是用户身份凭据，对应一个账户

2017-02-14 08:43 UTC, ekousp commented on zh-cn.md
> +    * AccessKey与用户一一对应是身份凭据之一, 请用户保管好自己的AccessKey。
不要中英文标点混用

2017-02-14 08:43 UTC, ekousp commented on zh-cn.md
>  * Path: 具体的 API 路径，参见下文定义
v1 格式为代码

2017-02-14 09:05 UTC, zzmmzz777 approved these changes

2017-02-14 09:06 UTC, merged